### ISSUE TITLE
Seria pro trabalho do Ricardo?  

### ISSUE THREAD

**Issue by TDamiao** [macielcjunior/BlogdaUnifeg#1]
Se for e precisar de ajuda me avisa, vocês estão usando Framework Bootstrap pra ser mais exato, não sei como ele vai aceitar mas caso quiser uma ajuda me avisai ai que eu do uma forcinha!  Abraço.

**Comment by macielcjunior** [comment]
É sim, vi a mensagem agora.. hehe desculple pela demora!
Abraço
